[package]
name = "rps"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28.0"
rand = "0.9.0"
weighted_rand = "0.4.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "new_benchmark"
harness = false
